routes:
  /podcast/rss/:
    template: podcast/rss
    content_type: text/xml
  /news/rss/:
    template: news/rss
    content_type: text/xml

collections:
  /:
    permalink: /{slug}/
    template: index
  /blog/:
    permalink: /blog/{slug}/
    filter: tag:blog+tag:-podcast
  /podcast/:
    permalink: /podcast/{slug}/
    filter: tag:podcast+tag:-blog
  /news/:
    permalink: /news/{slug}/
    filter: tag:news+tag:-blog

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
